spring:
  datasource:
    url: jdbc:h2:mem:uaa_db
    username: root
    password: root
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console # default

  # flyway
  flyway:
    enable: true
    locations: classpath:/dev/db/migration/h2

# jwt
jwt:
  expiration: 24 # in hours
  secret: bob-marley